### ISSUE TITLE
Client error when launching 1.21.4 Fabric

### ISSUE THREAD

**Issue by ButterKing-28** [LouisQuepierts/WhatImPressing#1]
When launching the game I received this error:

`The game crashed: initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'wip' at 'net.quepierts.wip.WhatImPressing'!`
Error code: -1

**Comment by ButterKing-28** [comment]
Here is more on the crash log

`Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'wip' at 'net.quepierts.wip.WhatImPressing'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:476)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/CoreShaderRegistrationCallback
	at knot//net.quepierts.wip.WhatImPressing.onInitializeClient(WhatImPressing.java:22)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more`

**Comment by igameshat** [comment]
i got the same exact issue

**Comment by LouisQuepierts** [comment]
Sorry to have happened, but version 1.21-21.1.1 do not support Minecraft versions other than 1.21 and 1.21.1.
You might try to used 1.21.2-21.1.2, it could work on Minecraft 1.21.2 ~ 1.21.4
